bookshelf/urls.py
from django.contrib import admin
from django.urls import path, include
# from shelf.views import load_home_page, get_books, add_book_form, add_book, delete_book, edit_book, add_comment, view_book_detail, add_comment, add_like, remove_like
from shelf.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', get_books, name='home'),
    path('add_book_form/', add_book_form, name='add_book_form'),
    path('add_book/', add_book, name="add_book"),
    path('delete_book/<book_id>', delete_book, name='delete_book'),
    path('edit_book/<book_id>', edit_book, name='edit_book'),
    path('book_detail/<book_id>', view_book_detail, name='book_detail'),
    path('add_comment/<book_id>', add_comment, name='add_comment'),
    path('like/<book_id>', add_like, name='add_like'),
    path('unlike/<book_id>', remove_like, name='remove_like'),
    path('my_books/', get_my_books, name='my_books'),
    path('favorites/', get_favorites, name='favorites'),
    path('books_by_owner/<owner_id>', books_by_owner, name='books_by_owner'),
    path('search/', perform_search, name='perform_search'),
    path('delete_comment/<comment_id>', delete_comment, name='delete_comment'),
    path('update_comment/<comment_id>', update_comment, name='update_comment'),
]

shelf/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Create your models here.
class Shelf(models.Model):
    title = models.CharField(max_length=100, default="My Shelf")


class Book(models.Model):
    GENRES = [
        ('fan', 'Fantasy'),
        ('adv', 'Adventure'),
        ('rom', 'Romance'),
        ('dys', 'Dystopian'),
        ('mys', 'Mystery'),
        ('hor', 'Horror'),
        ('thrill', 'Thriller'),
        ('hisfic', 'Historical Fiction'),
        ('scifi', 'Science Fiction'),
        ('bio', 'Biography'),
        ('cook', 'Cookbook'),
        ('mot', 'Motivational'),
        ('health', 'Health'),
        ('his', 'History'),
        ('travel', 'Travel'),
        ('diy', 'How-to'),
        ('sci', 'Science'),
        ('math', 'Math')
    ]

    COVER_URLS = {
        'fan': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673269245/assets/book_covers/cover_fantasy_jzdbyb.jpg',
        'adv': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673269245/assets/book_covers/cover_adventure_nslq2f.jpg',
        'rom': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673269245/assets/book_covers/cover_romance_ed8yc8.jpg',
        'dys': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673269245/assets/book_covers/cover_dystopia_vzvsx7.jpg',
        'mys': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673272296/assets/book_covers/cover_mystery_bxumol.jpg',
        'hor': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673272205/assets/book_covers/cover_horror_pjafgt.jpg',
        'thrill': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673269245/assets/book_covers/cover_thriller_neqvi9.jpg',
        'hisfic': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673270932/assets/book_covers/cover_hisfic_dkiorh.jpg',
        'scifi': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673269245/assets/book_covers/cover_scifi_zavbdy.jpg',
        'bio': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673269245/assets/book_covers/cover_bio_szb7x2.jpg',
        'cook': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673269760/assets/book_covers/cover_cookbook_k8fuqz.jpg',
        'mot': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673269760/assets/book_covers/cover_motivation_tmlbib.jpg',
        'health': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673270018/assets/book_covers/cover_health_lfdgjr.jpg',
        'his': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673270319/assets/book_covers/cover_history_oajjvt.jpg',
        'travel': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673270505/assets/book_covers/cover_travel_ortf8u.jpg',
        'diy': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673270719/assets/book_covers/cover_howto_v00rx2.jpg',
        'sci': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673332629/assets/book_covers/cover_science_lqzaum.jpg',
        'math': 'https://res.cloudinary.com/dzg7yacrw/image/upload/v1673332629/assets/book_covers/cover_maths_mtobkq.jpg'
    }

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    genre = models.CharField(max_length=6, choices=GENRES)
    likes = models.ManyToManyField(User, blank=True, related_name="book_likes")
    image_url = models.URLField(default="https://res.cloudinary.com/dzg7yacrw/image/upload/v1673273165/assets/book_covers/cover_placeholder_vqd1hn.jpg")
    posted_on = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    def number_of_like(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse("book_detail",  kwargs={"slug": self.slug})


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="comments")
    body = models.TextField()
    written_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['written_on']

    def __str__(self):
        return f"Comment: {self.body} by {self.author}"

templates/add_book_template.html
{%extends "base.html"%}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
<h2 class="display-2">Add a Book</h2>
<form method="POST" action="/add_book/">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-secondary">Submit</button>
</form>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="A site for book lovers to share what they are reading.">
  <meta name="keywords" content="books, blog, reading, stories">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous">
  </script>

  <link rel="stylesheet"
    href="https://res.cloudinary.com/dzg7yacrw/raw/upload/v1673277978/static/css/style.c73845544dd2.css">
  <title>BookShelf</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
      <div class="container">
        <span class="navbar-brand mb-0 h1">BookShelf</span>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navmenu">
          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="/my_books/" class="nav-link">My Books</a></li>
            <li class="nav-item"><a href="/favorites/" class="nav-link">Favorites</a></li>
            <li class="nav-item"><a href="/add_book_form/" class="nav-link">Add a Book</a></li>
            <li class="nav-item"><a href="{% url 'account_logout' %}" class="nav-link">Sign Out</a></li>

            {% else %}
            <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link">Sign In</a></li>
            <li class="nav-item"><a href="{% url 'account_signup' %}" class="nav-link">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </div>

    </nav>
  </header>

  <!--BEGIN Markup for displaying messages.-->
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        {% for message in messages %}
        {% if message.tags == 'alert-success' or message.tags == 'alert-danger' %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
          {{ message | safe }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>

  {% for message in messages %}
  {% if message.tags == 'alert-info' %}
  <script src="https://code.jquery.com/jquery-3.6.3.min.js"
    integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
  <script>
    $(document).ready(function () {
      $("#alert-modal").modal('show');
      $("#modal-text").text("{{ message | safe}}")
    });
  </script>
  {% endif %}
  {% endfor %}
  <!--END Markup for displaying messages.-->


  {% block content %}
  {% endblock %}

  <!--Footer-->
  <footer class="fixed-bottom text-center text-lg-start bg-light text-muted">
    <section class="d-flex justify-content-center   p-4 border-bottom">
      <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#credits-modal">View Image
        Credits</button>
    </section>
  </footer>

  <!-- Success Modal Dialog-->
  <div id="alert-modal" class="modal fade" tabindex="-1" aria-labelledby="modal-label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal-label">Excellent!</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p class="text-center"><i id="modal-success-icon" class="fa-regular fa-circle-check"></i></p>
          <p id="modal-text" class="text-center"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <!--Image Credits Modal Dialog-->
  <div id="credits-modal" class="modal fade " tabindex="-1" aria-labelledby="modal-credit-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal-credit-title">Image Credits</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

          <ul>
            <li>Login Page: <a href="https://www.pexels.com/photo/pages-on-an-opened-book-415071/" target="_blank">Pixabay</a></li>
            <li>Empty Results: <a
                href="https://www.freepik.com/free-vector/empty-concept-illustration_7117865.htm#query=no%20data&position=2&from_view=search&track=sph" target="_blank">storyset</a>
              on Freepik</li>
            <li>Signup Page: <a href="https://undraw.co/illustrations" target="_blank">unDraw Illustrations</a></li>
            <li>Question Mark: <a href="https://www.flaticon.com/free-icons/question"  target="_blank">Flaticon</a></li>
            <li>404 Error Page: <a
                href="https://www.freepik.com/free-vector/internet-network-warning-404-error-page-file-found-web-page-internet-error-page-issue-found-network-404-error-present-by-man-sleep-display_21586054.htm#query=404%20page&position=3&from_view=search&track=sph" target="_blank">jcomp</a>
              on Freepik</li>
            <li>Fantasy Cover: <a
                href="https://www.freepik.com/free-vector/black-spooky-castle-flying-dragon-canyon-with-mountains-forest-cartoon-fantasy-illustration-with-medieval-palace-with-towers-creepy-beast-with-wings-rocks-pine-trees_12207978.htm#query=fantasy&position=1&from_view=search&track=sph" target="_blank">Image
                by upklyak</a> on Freepik</li>
            <li>Adventure Cover: <a
                href="https://www.freepik.com/free-vector/camping-place-cartoon-composition-with-yellow-tent-lamp-pot-with-dinner-fire-night-sky_13749110.htm#query=adventure&position=21&from_view=search&track=sph" target="_blank">Image
                by macrovector</a> on Freepik</li>
            <li>Romance Cover: <a
                href="https://www.freepik.com/free-photo/paper-valentines-day-hearts-pink_3915611.htm#query=romance&position=41&from_view=search&track=sph" target="_blank">Image
                by valeria_aksakova</a> on Freepik</li>
            <li>Mystery Cover: <a
                href="https://www.freepik.com/free-photo/mobile-smartphone-magnifier-notebook-with-leather-cover-isolated-black-farm-wooden-table_11333683.htm#query=mystery&position=27&from_view=search&track=sph" target="_blank">Image
                by bublikhaus</a> on Freepik </li>
            <li>Horror Cover: <a
                href="https://www.freepik.com/free-vector/frightening-halloween-realistic-background_3824490.htm#query=horror&position=2&from_view=search&track=sph" target="_blank">Image
                by vectorpouch</a> on Freepik </li>
            <li>Thriller Cover: <a
                href="https://www.freepik.com/free-vector/crime-scene-night-murder-place-dark-room_6823044.htm#query=thriller&position=3&from_view=search&track=sph" target="_blank">Image
                by vectorpouch</a> on Freepik</li>
            <li>Science Fiction Cover: <a
                href="https://www.freepik.com/free-photo/alien-planet-building_14541108.htm#query=science%20fiction&position=10&from_view=search&track=sph" target="_blank">Image
                by liuzishan</a> on Freepik </li>
            <li>Biography Cover: <a
                href="https://www.freepik.com/free-vector/social-biography-concept-illustration_12704426.htm#query=biography&position=45&from_view=search&track=sph" target="_blank">Image
                by storyset</a> on Freepik</li>
            <li>Dystopia Cover: <a
                href="https://www.pexels.com/photo/person-in-brown-coat-and-black-pants-standing-on-gray-concrete-floor-4888474/" target="_blank">cottonbro
                studio</a></li>
            <li>Cookbook Cover: <a
                href="https://www.freepik.com/free-vector/set-people-cooking-their-favourite-food_8247921.htm#query=cooking&position=0&from_view=search&track=sph" target="_blank">Image
                by pikisuperstar</a> on Freepik</li>
            <li>Motivation Cover: <a
                href="https://www.freepik.com/free-photo/hikers-top_7630716.htm#query=motivation&position=3&from_view=search&track=sph" target="_blank">Image
                by wirestock</a> on Freepik</li>
            <li>Health Cover: <a
                href="https://www.freepik.com/free-photo/doctors-hands-holding-medical-care-objects_18417027.htm#query=health&position=5&from_view=search&track=sph" target="_blank">Image
                by rawpixel.com</a> on Freepik</li>
            <li>History Cover: <a
                href="https://www.pexels.com/photo/stonehenge-under-nimbostratus-clouds-161798/" target="_blank">Pixabay</a></li>
            <li>Travel Cover: <a href="https://www.pexels.com/photo/woman-looking-at-the-map-3935702/" target="_blank">Leah Kelley</a>
            </li>
            <li>How-to Cover: <a
                href="https://www.pexels.com/photo/man-holding-wooden-stick-while-drilling-hole-1094767/" target="_blank">Thijs van der
                Weide</a></li>
            <li>Historical Fiction Cover: <a
                href="https://www.pexels.com/photo/focused-woman-in-old-outfit-reading-book-with-oil-lamp-4145059/" target="_blank">JJ
                Jordan</a></li>
            <li>Placeholder Image: <a
                href="https://www.pexels.com/photo/selective-focus-photography-of-white-softbound-book-267586/" target="_blank">Photo by
                Pixabay</a> </li>
            <li>Science Cover: <a
                href="https://www.freepik.com/free-vector/science-laboratory-composition_21078541.htm#query=science&position=17&from_view=search&track=sph" target="_blank">Image
                by macrovector</a> on Freepik</li>
            <li>Maths Cover: <a
                href="https://www.freepik.com/free-vector/math-background_4365871.htm#query=mathematics&position=13&from_view=search&track=sph" target="_blank">Freepik</a>
            </li>
            <li>Comments Image: <a
                href="https://www.freepik.com/free-vector/reviews-concept-landing-page_5168344.htm#query=comments&position=20&from_view=search&track=sph" target="_blank">Freepik</a>
            </li>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <script src="https://kit.fontawesome.com/6a251fd2ee.js" crossorigin="anonymous"></script>
  <script>
    setTimeout(function () {
      let messages = document.getElementById('msg');
      let alert = new bootstrap.Alert(messages);
      alert.close();
    }, 2500);
  </script>

  <script src="https://code.jquery.com/jquery-3.6.3.min.js"
    integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
</body>

</html>

templates/edit_book_template.html
{%extends "base.html"%}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    
<h2 class="display-2">Edit Book</h2>

<form method="POST" >
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-secondary">Save Changes</button>
</form>

</div>
{% endblock %}

templates/hello_template.html
{%extends "sample_base.html"%}

{% block content %}
<h2>This is injected content.</h2>
<p>I am the content injected into the template.</p>
{% endblock %}

templates/index.html
{%extends "base.html"%}

{% block content %}

<div class="container">
    <!--BEGIN Display the heading-->
    <div class="row justify-content-between">
        <div class="col-4">
            {% if heading_label%}
            <h2 class="display-3">{{ heading_label }}</h2>
            {% else%}
            <h2 class="display-3">Books</h2>
            {% endif %}
        </div>
        <div class="col-4 text-end my-auto">
            <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                <i id="search-icon" class="fa-solid fa-magnifying-glass"></i>
            </button>
        </div>
    </div>
    <!--END Display the heading-->

    {% if books %}

    <!--START Display Books-->
    <div class="row">
        <div class="col-12 mt-3">
            <div class="row my-3 g-0 d-flex justify-content-center">

                {% for book in books %}
                <div class="card mx-3 my-2" style="width: 22rem;">

                    <img src="{{book.image_url}}" class="card-img-top"
                        alt="An image to describe the genre {{book.get_genre_display}}">

                    <div class="card-body">
                        <h4 class="card-title text-center">{{book.title}}</h5>
                            <h5 class="card-subtitle mb-2 text-muted">{{book.author}}</h6>
                                <h5 class="card-subtitle mb-2 text-muted">{{book.get_genre_display}}</h6>
                                    <h6 class="card-subtitle mb-2 text-muted">Posted on {{ book.posted_on }}</h6>

                                    <hr class="hr">
                                    <p class="card-text">{{book.description}}</p>
                                    <hr class="hr">
                                    {% if book.owner == user%}
                                    <p class="card-text text-end">Posted by {{book.owner}} </p>
                                    {% else %}
                                    <p class="card-text text-end">Posted by <a
                                            href="/books_by_owner/{{book.owner.id}}">{{book.owner}}</a> </p>
                                    {% endif%}


                    </div>

                    <div class="card-footer text-center">

                        {% if book.owner == user %}
                        <a href="/edit_book/{{book.id}}" class="card-link"><i
                                class="fa-regular fa-pen-to-square"></i></a>
                        <a href="/delete_book/{{book.id}}" class="card-link"><i class="fa-regular fa-trash-can"></i></a>
                        {% endif %}
                        <a href="/book_detail/{{book.id}}" class="card-link">
                            <i class="fa-regular fa-comment"></i> {{ book.comments.count }}
                        </a>
                        {% if book.id in liked_books %}
                        <a href="/unlike/{{book.id}}" class="card-link"><i class="fa-solid fa-heart"></i>
                            {{ book.number_of_like }}</a>
                        {% else %}
                        <a href="/like/{{book.id}}" class="card-link"><i class="fa-regular fa-heart"></i>
                            {{ book.number_of_like }}</a>
                        {% endif %}

                    </div>
                </div>

                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row  my-3 g-0 d-flex justify-content-center">

                {% endif %}

                {% endfor %}

            </div>

        </div>

    </div>
    <!--END Display Books-->

    <!--BEGIN Pagination Code-->
    {% if books.has_other_pages %}
    <ul class="pagination justify-content-center">
        {% if books.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ books.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        {% endif %}
        {% for i in books.paginator.page_range %}
        {% if books.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }}</span></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if books.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ books.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
    <!--END Pagination Code-->

    {% else %}
    <!--Display empty list content.-->
    <div class="row justify-content-center text-center">
        <div class="col-6">
            <p class="display-6">Looks like I have no books to display.</p>
            <img src="https://res.cloudinary.com/dzg7yacrw/image/upload/v1673264914/assets/site_images/no_results_w3u5d8.jpg"
                class="img-fluid" alt="Empty shelf.">
        </div>
    </div>

    {% endif %}

    <!-- Search Modal Form -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Search</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="container-fluid">

                        <form action="/search/" method="POST">
                            {% csrf_token %}

                            {% if genres %}
                            <h3>Genre</h3>

                            <div class="row">
                                {% for genre in genres %}
                                <div class="col-md-6">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="{{ genre.0 }}"
                                            id="{{ genre.0 }}" name="genres">
                                        <label class="form-check-label" for="{{ genre.0 }}">
                                            {{ genre.1 }}
                                        </label>
                                    </div>
                                </div>
                                {% if forloop.counter|divisibleby:2 %}
                            </div>

                            <div class="row">
                                {% endif %}
                                {% endfor %}

                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="title-search-input">Title</label>
                                            <input type="text" class="form-control" id="title-search-input"
                                                name="title-search-input">
                                        </div>

                                        <div class="form-group">
                                            <label for="author-search-input">Author</label>
                                            <input type="text" class="form-control" id="author-search-input"
                                                name="author-search-input">
                                        </div>

                                        <div class="form-group">
                                            <label for="description-search-input">Description Search</label>
                                            <input type="text" class="form-control" id="description-search-input"
                                                name="description-search-input">
                                        </div>
                                    </div>
                                </div>
                                {% else %}
                                <p>Woops. Something didn't load properly.</p>
                                {% endif %}

                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Search</button>
                            </div>
                            
                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
    {% endblock %}

templates/sample_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

   
    <!--
This is how you would link to static stylesheet.
If it is a normal css from a CDN, you can just use it as is.

    -->

    <link rel="stylesheet" href="{% static 'css/test_style.css' %}">
    <title>Hello Bookshelf Base</title>
</head>
<body>


    {% block content %}
    {% endblock %}

    <footer>
        For all those who love the printed word.
    </footer>
    
</body>
</html>